### ISSUE TITLE
It is possible to create a tariff with negative "price" and "washingTime" values

### ISSUE THREAD

**Issue by aianushevich** [microservices-course-itmo/designing_microservices_course#53]
Method: POST /tariffs

**Body example:**
`{
  "name": "NegativeValues",
  "price": -3.5,
  "washingTime": -4
}`

**Result:** Successful response with code 201

**Conclusion:** It's necessary to disable possibility of creation tariffs with negative values.

**Comment by RusskovMatvey** [comment]
I created a pull request #57
