### ISSUE TITLE
It is possible to create tariff with non-unique name

### ISSUE THREAD

**Issue by aianushevich** [microservices-course-itmo/designing_microservices_course#55]
It would be preferable to disable possibility of creation tariffs with non-unique names.

E.g.
`[
  {
    "id": 25,
    "name": "NewTestTariff",
    "price": 4.67,
    "washingTime": 12
  },
  {
    "id": 26,
    "name": "NewTestTariff",
    "price": 4.67,
    "washingTime": 12
  }
]`

**Comment by RusskovMatvey** [comment]
I created a pull request https://github.com/microservices-course-itmo/designing_microservices_course/pull/57
